spring:
  application:
    name: kafka-batch
  kafka:
    bootstrap-servers: 172.16.1.65:9092  # 指定 Kafka Broker 地址，可以设置多个，以逗号分隔
    producer:
      acks: 1  # 0-不应答。1-leader 应答。all-所有 leader 和 follower 应答。
      retries: 3  # 发送失败时，重试发送的次数
      key-serializer: org.apache.kafka.common.serialization.StringSerializer # 消息的 key 的序列化
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer # 消息的 value 的序列化
      batch-size: 16384  # 每次批量发送消息的最大数量
      buffer-memory: 33554432 # 每次批量发送消息的最大内存
      properties:
        linger:
          ms: 30000 # 批处理延迟时间上限。这里配置为 30 * 1000 ms 过后，不管是否消息数量是否到达 batch-size 或者消息大小到达 buffer-memory 后，都直接发送一次请求。
    consumer:
      auto-offset-reset: earliest  # 设置消费者分组最初的消费进度为 earliest 。可参考博客 https://blog.csdn.net/lishuangzhe7047/article/details/74530417 理解
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer # 消息的 key 的反序列化
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer # 消息的 value 的反序列化
      properties:
        spring:
          json:
            trusted:
              packages: com.zss.kafka.message

    listener:
      missing-topics-fatal: false  # 消费监听接口监听的主题不存在时，默认会报错。所以通过设置为 false ，解决报错